name: PickingTips
main: com.github.insdreamb.pickingtips.PickingTips
version: 1.1.5
softdepend:
  - RPG_Items
  - MiaoChat
commands:
  tips:
permissions:
  PickingTips.block:
    default: true
  PickingTips.reload:
    default: op
  PickingTips.show:
    default: true
  PickingTips.help:
    default: true